name: digi_kot
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.3
  flutter: 
    sdk: flutter
  google_fonts: ^2.3.2
  google_maps_flutter: ^2.1.5
  permission_handler: ^9.2.0
  geolocator: ^8.2.1
  flutter_spinkit: ^5.1.0
  flutter_dotenv: ^5.0.2
  flutter_config: ^2.0.0
  flutter_polyline_points: ^1.0.0
  mobile_scanner: ^1.1.0
  timeline_tile: ^2.0.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - .env
